#!/usr/bin/env python
from subprocess import check_output
import sys

# count running job cores for somebody ($1)

username = sys.argv[1]

cores = 0

qstat = check_output("sqwholong %s" % username, shell=True)

for line in qstat.splitlines():
    split = line.split()
    if len(split) != 10:
        continue
    if split[4] != "R":
        continue
    cores += int(split[8])

print cores
