#!/bin/bash

# Show info about my jobs in the queue output: default, but added
# number of CPUS and time limit, also support extra output flags

EXTRA_OPTIONS="$1"

squeue -u $(whoami) -o "%.12i %.9P %.8j %.8u %.2t %.19S %.10M %.10l %.6D %.6C $EXTRA_OPTIONS"
