#!/usr/bin/env python
from subprocess import check_output
from sys import argv, exit
import re

# pass a jobid as a command line argument
# the current regular output of the job is printed to standard out

jobid = argv[1]
command='cat'

if (jobid in ['-h','--help']):
    print "OPTIONS\n   -c, --command: changes the output command to specified value. Default: cat\nEXAMPLE\n   qpeekout jobid123.cheops -c 'head -n 30' "
    exit()
if (len(argv)>2):
    if (argv[2] in ['-c','--command']):
        command=argv[3]
qstatf = check_output("qstat -f %s" % jobid, shell=True)
m = re.search(r'exec_host = (cheops\d\d\d\d\d)/', qstatf)
try:
    node = m.group(1)
    print node
except:
    print "Can't parse output of qstat -f %s" % jobid
else:
    if not re.match(r'\d+\..+', jobid):
        jobid += '.cheops10'
    print check_output('ssh %s %s /var/spool/torque/spool/%s.OU' % (node, command, jobid), shell=True)

